{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.app.name }}-hpa
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.app.name }}
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.app.name }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.autoscaling.metrics.cpu.enabled }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.metrics.cpu.targetAverageUtilization }}
  {{- end }}
  {{- if .Values.autoscaling.metrics.memory.enabled }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.metrics.memory.targetAverageUtilization }}
  {{- end }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.autoscaling.behavior.scaleDown.stabilizationWindowSeconds }}
      policies:
      - type: Percent
        value: {{ .Values.autoscaling.behavior.scaleDown.percent }}
        periodSeconds: {{ .Values.autoscaling.behavior.scaleDown.periodSeconds }}
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.autoscaling.behavior.scaleUp.stabilizationWindowSeconds }}
      policies:
      - type: Percent
        value: {{ .Values.autoscaling.behavior.scaleUp.percent }}
        periodSeconds: {{ .Values.autoscaling.behavior.scaleUp.periodSeconds }}
      - type: Pods
        value: {{ .Values.autoscaling.behavior.scaleUp.pods }}
        periodSeconds: {{ .Values.autoscaling.behavior.scaleUp.periodSeconds }}
      selectPolicy: Max
{{- end }}
